hcsp/create-an-empty-class-in-package

- src/main/java/my/cute/Cat.java
> 新添一个my.cute包，并且在包中新建一个Cat类。

- src/main/java/my/cute/Cat.java
> 在指定包创建了一个类cat

- src/main/java/my/cute/Cat.java
在默认包下（即src/main/java目录中）创建一个名为Cat的公开类
> 在指定包中创建一个类

- src/main/java/my/cute/Cat.java
> [A]创建一个Cat类

- src/main/java/my/cute/Cat.java
an empty class Cat has been created in package my.cute
> a public class Cat has been created in package my.cute

- src/main/java/my/cute/Cat.java
> 创建my/cute包，并初始化一个Cat类

- src/main/java/my/cute/Cat.java
> 在 my.cute 包中新建一个 Cat 公开类

- src/main/java/my/cute/Cat.java
> '在指定的包中创建一个类'

- src/main/java/my/cute/Cat.java
> Add Cat class in package

- src/main/java/my/cute/Cat.java
create an empty class in package!
> create an empty class in package!

- src/main/java/my/cute/Cat.java
> 在指定的包中创建一个类

- src/main/java/my/cute/Cat.java
> add one public class Cat

- src/main/java/my/cute/Cat.java
> feature：增加Cat类

- src/main/java/my/cute/Cat.java
> [增加] - 在包my.cute中新增一个类Cat

- src/main/java/my/cute/Cat.java
create a Cat class in my.cute package
> create a Cat class in my.cute package

- src/main/java/my/cute/Cat.java
> new class in package

- src/main/java/Cat.java
- src/main/java/my/cute/Cat.java
> create my/cute class Cat

- src/main/java/Cat.java
- src/main/java/my/cute/Cat.java
>  create my/cute class Cat

- src/main/java/my/cute/Cat.java
> 在指定包下创建了一个名为 `Cat` 的公开类

- src/main/java/my/cute/Cat.java
> 我已经在my cute包中创建了一个名为Cat的类

- src/main/java/my/cute/Cat.java
> 在my/cute中添加Cat类

- src/main/java/my/cute/Cat.java
package my.cute;  create new Cat CatTest
> package my.cute;  create new Cat CatTest

- src/main/java/my/cute/Cat.java
add src/main/java/my/cute/Cat.java
> add src/main/java/my/cute/Cat.java

- src/main/java/my/cute/Cat.java
create my.cute.Cat class
&&
fix test package
> fix test Cat

- src/main/java/my/cute/Cat.java
> Create Cat Class under my.cute package

- src/main/java/my/cute/Cat.java
> 在指定的包 my.cute 中创建类 Cat

- src/main/java/my/cute/Cat.java
> 这是第二次创建Cat类

- src/main/java/my/cute/Cat.java
> 正式开始的java代码练习2

- src/main/java/my/cute/Cat.java
> 在my.cute包中创建Cat公开类并通过测试

- src/main/java/my/cute/Cat.java
> 在指定的包名下添加Cat公开类

- src/main/java/my/cute/Cat.java
> 在My.cute包创建cat类

- src/main/java/my/cute/Cat.java
> 指定的包中建类0830bonnie

- src/main/java/my/cute/Cat.java
> 在指定的 package 里面创建了一个类

- src/main/java/my/cute/Cat.java
> 在指定包下建Cat类

- src/main/java/my/cute/Cat.java
> add Cat class in my.cute

- src/main/java/my/cute/Cat.java
> 在指定文件夹下建立Cat类

- src/main/java/my/cute/Cat.java
> debug source code

- src/main/java/my/cute/Cat.java
> creat package class

- src/main/java/my/cute/Cat.java
new package and new classs called Cat
> new package and new classs called Cat

- src/main/java/my/cute/Cat.java
> 在指定包中创建了一个Cat类

- src/main/java/my/cute/Cat.java
> 在my.cute包中创建了一个名为Cat的公开类

- src/main/java/my/cute/Cat.java
> add: 在my.cute包中（即src/main/java/my/cute目录中）创建了一个名为Cat的公开类

- src/main/java/my/cute/Cat.java
> 在指定包中创建了Cat类

- src/main/java/my/cute/Cat.java
> 每个类都包含在一个包内，包的名字由类所在的目录决定。

- src/main/java/my/cute/Cat.java
> 在指定包下面创建一个类，类的全限定名由类所在的包名（或者目录）确定。

- src/main/java/my/cute/Cat.java
> 在src/main/java/my/cute中创建了了Cat公开类

- src/main/java/my/cute/Cat.java
> 在指定包中创建一个Cat类

- src/main/java/my/cute/Cat.java
- src/test/java/my/cute/Cat.java
> submit again

- src/main/java/my.cute/Cat.java
- src/main/java/my/cute/Cat.java
> 在my.cute下创建Cat类

- src/main/java/my/cute/Cat.java
> 创建一个名为Cat的公开类

- src/main/java/my/cute/Cat.java
> 创建my.cute包，增加Cat类

- src/main/java/my/cute/Cat.java
> 在 my.cute 包中新建 Cat 类

- src/main/java/my/cute/Cat.java
> 创建my.cute包及Cat类

- src/main/java/my/cute/Cat.java
- src/test/java/my/cute/Cat.java
> A：往包里面添加一个类

- src/main/java/my/cute/Cat.java
- src/test/java/my/cute/Cat.java
> A：往包里添加一个类

- src/main/java/my/cute/Cat.java
> first commit

- src/main/java/my/cute/Cat.java
> second commit

- src/main/java/my/cute/Cat.java
> 在指定的包中建了一个类

- src/main/java/my/cute/Cat.java
> my first commit

- src/main/java/my/cute/Cat.java
> 在my.cute包中（即src/main/java/my/cute目录中）创建一个名为Cat的公开类

- src/main/java/my/cute/Cat.java
> 在指定包中创建一个类Cat

- src/main/java/my/cute/Cat.java
> my.cute包中创建一个名为Cat的公开类

- src/main/java/my/cute/Cat.java
> create a new class Cat in the package "my.cute"

- src/main/java/my/cute/Cat.java
> add Cat class with package

- src/main/java/my/cute/Cat.java
> 在my.cute中新建Cat类

- src/main/java/my/cute/Cat.java
> crate a new Class -Cat

- src/main/java/my/cute/Cat.java
> 在指定包下创建Cat

- src/main/java/my/cute/Cat.java
> 在 my.cute 包中创建一个名为 Cat 的公开类

- src/main/java/my/cute/Cat.java
> add a new class

- src/main/java/my/cute/Cat.java
> from NervousOrange: Assignment 2 of class and package.

- src/main/java/my/cute/Cat.java
> 在main/java/my/cute目录下创建了Cat类。

- src/main/java/my/cute/Cat.java
> 在my.cute包中创建名为Cat的公共类

- src/main/java/my/cute/Cat.java
> 在指定的包中创建一个Cat类

- src/main/java/my/cute/Cat.java
在指定的包中创建一个类,so easy!(一开始远程拒绝了，后来发现是自己没有另外建分支)
> Richard1230 create an empty class in package

- src/main/java/my/cute/Cat.java
> 在指定包my.cute包中创建了Cat公开类

- src/main/java/my/cute/Cat.java
> 添加一个包中的Cat类

- src/main/java/my/cute/Cat.java
> 在my.cute包下创建Cat类

- src/main/java/my/cute/Cat.java
> 在指定包中创建cat公开类

- src/main/java/my/cute/Cat.java
> add a class to a package

- src/main/java/my/cute/Cat.java
> feat: 在指定的包中创建一个 public 的 Cat 类

- src/main/java/my/cute/Cat.java
> 创建my.cute Cat类

- src/main/java/my/cute/Cat.java
> 在 my.cute 包下的 Cat 类

- src/main/java/my/cute/Cat.java
> 在指定的包中创建名为 Cat 的类

- src/main/java/my/cute/Cat.java
> add new public class Cat

- src/main/java/my/cute/Cat.java
> add package

- src/main/java/my/cute/Cat.java
> my cute cat

- src/main/java/my/cute/Cat.java
新建目录 main/java/my/cute ，新建了一个公开类 Cat
> 新建目录 main/java/my/cute ，新建一个公开类 Cat

- src/main/java/my/cute/Cat.java
> 完成在指定包中创建指定类

- src/main/java/my/cute/Cat.java
> 在my.cute包中创建Cat类

- src/main/java/my/cute/Cat.java
> 指定包下创建Cat类

- src/main/java/my/cute/Cat.java
> 在my.cute包中新建Cat类

- src/main/java/my/cute/Cat.java
> cute包下创建Cat类

- src/main/java/my/cute/Cat.java
> 在my.cute包创建了Cat类

- src/main/java/my/cute/Cat.java
> my.cute包下新建Cat类

- src/main/java/my/cute/Cat.java
> 在my.cute包下创建了Cat类

- src/main/java/my/cute/Cat.java
> create a class 'Cat' in package

- src/main/java/my/cute/Cat.java
> Create Cat class in the specified package

- src/main/java/my/cute/Cat.java
> 创建指定目录下cat类

- src/main/java/my/cute/Cat.java
- src/main/java/my/cute/cat.java
> 在指定包中新建cat类

- src/main/java/my/cute/Cat.java
> Create an empty class Cat in package my.cute

- src/main/java/my/cute/Cat.java
> ceeate an empty class in package

- src/main/java/my/cute/Cat.java
> my.cute包中新建Cat类

- src/main/java/my/cute/Cat.java
> 第一节课的第二个课题，加油!

- src/main/java/my/cute/Cat.java
> add empty Cat public class in src.main.java.my.cute package.

- src/main/java/my/cute/Cat.java
> 指定包下创建一个Cat类

- src/main/java/my/cute/Cat.java
> 我创建了一个 Cat 的公开类

- src/main/java/my/cute/Cat.java
> 在my.cute包中创建一个Cat的公开类

- src/main/java/Cat.java
- src/main/java/my/cute/Cat.java
> create Cat class

- src/main/java/my/cute/Cat.java
> create cat in my.cute

- src/main/java/Cat.java
- src/main/java/my/cute/Cat.java
> Create cat class in package

- src/main/java/my/cute/Cat.java
> create an class in package

- src/main/java/my/cute/Cat.java
> feat: 完成创建一个 my.cute 包下的 Cat 类

- src/main/java/my/cute/Cat.java
> 在指定的包中新建了一个类

- src/main/java/my/cute/Cat.java
> 创建 `my/cute` 包, 和Cat类

- src/main/java/my/cute/Cat.java
> 在指定包中，新建Cat类

- src/main/java/my/cute/Cat.java
> finish task

- src/main/java/my/cute/Cat.java
> create cat class in my.cute

- src/main/java/my/cute/Cat.java
> 在指定的包中创建一个名为Cat的公开类

- src/main/java/my/cute/Cat.java
> Create a public class Cat in the my.cute package

- src/main/java/my/cute/Cat.java
> 完成了一个默认包下的类创建

- src/main/java/my/ cute/Cat.java
- src/main/java/my/cute/Cat.java
> 我在指定包中创建了一个Cat类

- src/main/java/my/cute/Cat.java
> 在my.cute包中创建Cat类.

- src/main/java/my/cute/Cat.java
> 创建一个 Cat 公开类

- src/main/java/my/cute/Cat.java
new  a cat class of my.cute package
> new a cat class of my.cute package

- src/main/java/my/cute/Cat.java
> feat: add Cat

- src/main/java/my/cute/Cat.java
> create an empty class in package

- src/main/java/my/cute/Cat.java
> add a class in package

- src/main/java/my/cute/Cat.java
在src/main/java/my/cute包中新建了一个Cat类。
> 在src/main/java/my/cute包中新建了一个Cat类。

- src/main/java/my/cute/Cat.java
> new Class 'Cat'

- src/main/java/my/cute/Cat.java
> jWang pullrequest

- src/main/java/my/cute/Cat.java
> 在my.cut包中创建一个Cat类

- src/main/java/my/cute/Cat.java
> Add New File: Cat.java

- src/main/java/my/cute/Cat.java
> 在指定的包my.cute中创建一个Cat类

- src/main/java/my/cute/Cat.java
第三天学习java，第二次pull request，同时也是想念博大的第304天，天有点热，想博大的心有点苦
> feat: 按照要求完成（指定的包中创建一个类），思念博大的304天

- src/main/java/my/cute/Cat.java
> add Cat class in package my.cute

- src/main/java/my/cute/Cat.java
> 指定的包中创建一个类

- src/main/java/my/cute/Cat.java
- src/main/java/my/cute/cat.java
> add a public class cat

- src/main/java/my/cute/Cat.java
> feature: create my cat

- src/main/java/my/cute/Cat.java
> 在my.cute包中创建一个Cat类

- src/main/java/my/cute/Cat.java
> 在包里创建 Cat 类

- src/main/java/my/cute/Cat.java
> create 'Cat' class in my/cute

- src/main/java/my/cute/Cat.java
> 指定包中创建Cat类

- src/main/java/my/cute/Cat.java
> my.cute.喵喵喵？？？

- src/main/java/my/cute/Cat.java
> created a main/java/my/cute/Cat.java file

- src/main/java/my/cute/Cat.java
> 在my.cute包中创建了类Cat

- src/main/java/my/cut/Cat.java
- src/main/java/my/cute/Cat.java
> 在指定的包中创建一个类 

- src/main/java/my/cute/Cat.java
在src/main/java/my/cute目录下创建了一个名叫Cat的公开类
> 在src/main/java/my/cute目录下创建了一个名叫Cat的公开类

- src/main/java/my/cute/Cat.java
> 在my.cute包中创建Cat公开类

- src/main/java/my/cute/Cat.java
> 请在my.cute包中创建一个名为Cat的公开类

- src/main/java/my/cute/Cat.java
- src/main/java/my/cute/a/Main.java
> Create Cat in my.cute Wu Zhenan

- src/main/java/my/cute/Cat.java
> 在指定的包名创建一个Cat类

- src/main/java/my/cute/Cat.java
> 在my.cute指定包中创建了一个Cat类

- src/main/java/my/cute/Cat.java
> 创建了一个名为Cat的类

- src/main/java/my/cute/Cat.java
> 新建了Cat类和my.cute包

- src/main/java/my/cute/Cat.java
> feat: create my cute Cat class

- src/main/java/my/cute/Cat.java
> feat(类): 在指定的包中创建类

- src/main/java/my/cute/Cat.java
> feat: create Cat.java in my.cute

- src/main/java/my/cute/Cat.java
> add a empty class Cat in package of src/main/java/my/cute

- src/main/java/my/cute/Cat.java
> 学生张博在指定包创建了一个类

- src/main/java/my/cute/Cat.java
> my.cute包中创建Cat类

- src/main/java/my/cute/Cat.java
> 这是在指定目录下创建包，清晰了默认目录与指定目录的区别

- src/main/java/my/cute/Cat.java
> 在my.cute包中创建了Cat类

- src/main/java/my/cute/Cat.java
> 练习在指定的包中创建一个类get。

- src/main/java/my/cute/Cat.java
> 在my/cute的包下面新建Cat

- src/main/java/Cat.java
- src/main/java/my/cute/Cat.java
> create inner class

- src/main/java/my/cute/Cat.java
> 在src\main\java\my\cute下创建类Cat

- src/main/java/my/cute/Cat.java
> feat: add my.cute.cat class

- src/main/java/my/cute/Cat.java
> create Cat class in specified package

- src/main/java/my/cute/Cat.java
> 在指定目录下创建一个公开类

- src/main/java/my/cute/Cat.java
> 在指定目录下新建cat

- src/main/java/my/cute/Cat.java
> 在指定的包重创建一个Cat类

- src/main/java/my/cute/Cat.java
> 在制定包中创建一个类

- src/main/java/my/cute/Cat.java
> feat: create an empty class in package

- src/main/java/my/cute/Cat.java
> feat: 在my.cute 中增加Cat类

- src/main/java/cute/Cat.java
- src/main/java/my/cute/Cat.java
> 在main.java.cute下创建Cat类

- src/main/java/my/cute/Cat.java
> my.cute下创建Cat

- src/main/java/my/cute/Cat.java
> create package class cat

- src/main/java/my/cute/Cat.java
> feat: 在特定包中创建类

- src/main/java/my/cute/Cat.java
> create a package and a class

- src/main/java/my/cute/Cat.java
> 创建cat在指定目录中

- src/main/java/my/cute/Cat.java
> 在my.cute中创建Cat类

- src/main/java/my/cute/Cat.java
> create a new Cat class in my.cute package

- src/main/java/my/cute/Cat.java
> 在my.cute包里新增Cat类

- src/main/java/my/cute/Cat.java
> 创建一个Cat类，完成

- src/main/java/my/cute/Cat.java
> feat:在指定的包中创建一个类

- src/main/java/my/cute/Cat.java
> 新增Cat类到my.cute包
